### ISSUE TITLE
Telegram gateway not configurable after installing the Mail Nextcloud app

### ISSUE THREAD

**Issue by didyouexpectthat** [nextcloud/twofactor_gateway#423] opened 2021-02-19 05:37 UTC
I used to use this and it worked great. Now I'm running Nextcloud 20.0.7 and want to add my bot token. All IDs fail.
Debian 10
PHP 7.3.19-1-deb10u1 
    with Zend OPcache v7.3.19-1~deb10u1, 

```
# occ twofactorauth:gateway:configure telegram
Please enter your Telegram bot token: 1234567980:abcde_fghij-_klmnopqr_stuvw
Using 1234567980:abcde_fghij-_klmnopqr_stuvw.
An unhandled exception has been thrown:
TypeError: Return value of "OCA\TwoFactorGateway\Command\Configure::execute()" must be of the type int, "null" returned. in /opt/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /opt/nextcloud/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /opt/nextcloud/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(OCA\TwoFactorGateway\Command\Configure), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/nextcloud/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/nextcloud/console.php(100): OC\Console\Application->run()
#5 /opt/nextcloud/occ(11): require_once('/opt/nextcloud/...')
#6 {main}
```

**Comment by didyouexpectthat** [comment] 2021-02-19 05:42
Looks to be an incompatibility with the Nextcloud mail app. I disabled the mail app and it worked fine.

**Comment by ChristophWurst** [comment] 2021-02-19 07:14
This app needs to be adjusted for https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#symfony-update

**Comment by ChristophWurst** [comment] 2021-02-19 07:15
duplicate of https://github.com/nextcloud/twofactor_gateway/issues/414

**Closed by ChristophWurst** 2021-02-19 07:15 UTC
