### ISSUE TITLE
Disabled Telegram two days before - enabled today, now the TG-ID will not work anymore

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/twofactor_gateway#118] opened 2018-09-22 11:56 UTC
Hi,

I've disabled the TG-Auth two days before, 'cause I did not setup the app-codes.
Today I wanted to enable again, but it's not able to verify my TG-ID.
Is this a bug?

Best

**Comment by ChristophWurst** [comment] 2018-09-24 05:45
Duplicate of https://github.com/nextcloud/twofactor_gateway/issues/109.

**Closed** 2018-09-25 19:00 UTC
