### ISSUE TITLE
Telegram Gateway | UnexpectedValueException: Only integers, floats and strings are allowed as value

### ISSUE THREAD

**Issue by djpremier** [nextcloud/twofactor_gateway#106] opened 2018-08-28 02:47 UTC
I'm from Brazil and the stack of errors below has occurred.

[nextcloud (1).log](https://github.com/nextcloud/twofactor_gateway/files/2326299/nextcloud.1.log)

**Comment by ChristophWurst** [comment] 2018-08-28 11:45
Duplicate of #86. It looks like you didn't initiate a conversation with your telegram bot before trying to enable the app. 

Could you please provide a detailed list of what you did before you got the error?

**Comment by ChristophWurst** [comment] 2018-08-28 11:45
Let's continue in #86 and close this one.

Thanks a lot for reporting this!

**Closed by ChristophWurst** 2018-08-28 11:45 UTC
Labels: bug
